### PR TITLE
add member option | firebase added | auto load members

### PR DESCRIPTION
**Pull request by v-aibha-v-jain**
added a button, which allows user to create new data json on firebase
linked a firebase (realtime database) 
use api to add up data in the page
a simple p tag with "loading.." text for better user experience

### CODE REVIEW

**Comment by EuclidStellar** [comment]
cool work @v-aibha-v-jain  can you please add details of existing members of this project and their details in Firebase so that their cars will also show on the website :) also please give me the access of the firebase project that you have used in this project :)
@euclidstellar 
euclidstellar@gmail.com

**Comment by v-aibha-v-jain** [comment]
ya sure
does that mean my pr would be accepted? 😁

**Comment by EuclidStellar** [comment]
Yes if it worked well on running checks

**Comment by v-aibha-v-jain** [comment]
noice!!! I guess u have received a mail for invitation for firebase elcostra

**Comment by v-aibha-v-jain** [comment]
added all possible existing members details in firebase
some of them got rejected bez of missing values

**Comment by EuclidStellar** [comment]
Thanks I'm a bit busy for 2 days I'll review and merge the PR asap :)
Thanks for an amazing contribution

**Comment by v-aibha-v-jain** [comment]
peace peace

**Comment by v-aibha-v-jain** [comment]
bro :)........

**Review by EuclidStellar — APPROVED** [review]

**Pull request merged**
