### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by kjl98**
Solved issue #40

### CODE REVIEW

**Comment by EuclidStellar** [comment]
hi @kjl98 raise an issue first and then mention that issue ticket number in description of this PR

**Comment by kjl98** [comment]
Please assigned me these labels - hacktoberfest 2024 , gssoc-extd

**Review by EuclidStellar — APPROVED** [review]

**Comment by kjl98** [comment]
"Hey [@EuclidStellar ], I just wanted to extend a massive thank you for merging my changes into your repository. Your project has been incredibly inspiring, and I'm thrilled to have contributed. Looking forward to collaborating more in the future!"

Just something from the heart. Always lands well. 🌟

Regards @kjl98

**Comment by kjl98** [comment]
Sir, can you please set the labels - hacktoberfest, gssoc-extd 24

**Pull request merged**
